#ifndef APP_CONSTS_H_INCLUDED
#define APP_CONSTS_H_INCLUDED

#define STUDENT_NAME_LEN  64
#define PROGRAM_NAME_LEN  32
#define STUDENT_EMAIL_LEN 64
#define ADMISSION_STATUS  8

#endif // APP_CONSTS_H_INCLUDED
